name: Node CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["10.x"]

    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: |
          npm install
      - name: Lint
        run: |
          npm run lint
        env:
          CI: true
      - name: Build
        run: |
          npm run build
        env:
          CI: true
