name: coins20 nofitication

on:
  push:
    branches:
      - master
    paths:
      - 'src/contents/**'

jobs:
  discord_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Generate description
        id: generate_description
        run: |
          diff=$(
            curl -fsS \
              -H 'Accept: application/vnd.github.diff' \
              -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
              "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}" \
                 | tail -n +3 \
                 | jq -saR . \
                 | sed 's/^"//; s/"$//'
          )

          description="\`\`\`diff\n${diff}\`\`\`"
          [ $(grep -o '\\n' <<< "$diff" | wc -l) -gt 20 ] && description="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"

          echo "::set-output name=description::${description//'%'/'%25'}"
      - name: Generate heading
        id: generate_heading
        run: |
          heading=$(
            sed '/Merge pull request/d; /^[[:space:]]*$/d; s/"/\\"/g' <<< '${{ github.event.head_commit.message }}' \
              | head -n 1 \
              | jq -saR . \
              | sed 's/^"//; s/"$//'
          )

          echo "::set-output name=heading::${heading//'%'/'%25'}"
      - name: Trigger Webhook
        run: |
          curl -fsS -XPOST \
            -H 'Content-Type:application/json' \
            "${{ secrets.COINS20_DISCORD_WEBHOOK_URL }}" \
            -d @- << EOS
              {
                "username": "coins-shinkan",
                "avatar_url": "https://raw.githubusercontent.com/coins-shinkan/shinkan-web-20/master/src/imgs/coins.png",
                "content": "新歓Webが更新されます。",
                "embeds": [
                  {
                    "title": "更新の詳細",
                    "description": "**${{ steps.generate_heading.outputs.heading }}**\n${{ steps.generate_description.outputs.description }}",
                    "timestamp": "${{ github.event.head_commit.timestamp }}",
                    "url": "https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
                  },
                  {
                    "title": "新歓Web",
                    "url": "https://coinshinkan.com/",
                    "description": "https://coinshinkan.com/"
                  }
                ]
              }
          EOS
