name: coins20 nofitication

on:
  push:
    branches:
      - master
    paths:
      - 'src/contents/**'

jobs:
  discord_webhook:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -fsS -XPOST \
            -H 'Content-Type:application/json' \
            "${{ secrets.COINS20_DISCORD_WEBHOOK_URL }}" \
            -d @- << EOS
              {
                "username": "coins-shinkan",
                "avatar_url": "https://raw.githubusercontent.com/coins-shinkan/shinkan-web-20/master/src/imgs/coins.png",
                "content": "新歓サイトが更新されます。https://coinshinkan.com/\n更新の詳細: https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
              }
          EOS
